### PR TITLE
#161580148 builds the sign-up page

### PR DESCRIPTION
**Pull request by Sm0k3s**
#### What does this PR do?
Builds the sign-up page
#### Description of Task to be completed?
Have fields for filling out the necessary registration information
#### What are the relevant pivotal tracker stories?
161580148
#### Screenshots (if appropriate)
signup

### CODE REVIEW

**Comment by ChegeBryan** [comment]
Straight up simplicity.  :thumbsup:
You could check the PR naming its not consistent with the last PR
[PR naming](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices)

**Comment by Sm0k3s** [comment]
I'll look into it, thanks

**Comment by Kitingu** [comment]
looks good

**Comment by kelvinndmo** [comment]
some awesome work....good work

**Pull request merged**
